### ISSUE TITLE
 error: 'Serial1'

### ISSUE THREAD

**Issue by AlfMueller** [lbuchs/wv-uart-fingerprint#1]
Error in Call (create instance)

WvFingerprint myfp(Serial1, RST_PIN, WAKE_PIN);

Error:
GetFingerprint:10:20: error: 'Serial1' was not declared in this scope

Thanks Alf from bastelgarage.ch

**Comment by lbuchs** [comment]
Serial1 is the port which the fingerprint device is connected to. If you using a arduino device, it may not have two serial ports, see https://www.arduino.cc/reference/en/language/functions/communication/serial/

Testing a Serial Device without multiple serial ports is not easy because you cannot use the serial port for debug messages. I would recommend a Ardiuno Mega or a ESP32 which have multiple serial ports.
